/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description [PostgREST] Reads from `profiles` table joined with `auth.users`. Actual PostgREST URL: `GET /rest/v1/profiles?id=eq.<user_id>`. Supabase RLS ensures users can only read their own row.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile (full_name, avatar_url)
         * @description [PostgREST] Updates `profiles` table. RLS allows owner update only. Actual PostgREST URL: `PATCH /rest/v1/profiles?id=eq.<user_id>`.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's learning stats
         * @description [PostgREST] Reads from `user_stats` table. Actual PostgREST URL: `GET /rest/v1/user_stats?user_id=eq.<user_id>`. RLS ensures users only see their own stats.
         */
        get: operations["getMyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Override a user's stats (admin / migration tool only)
         * @description Requires Supabase **service role key** in Authorization header (not a user JWT). Used for data migrations or admin corrections. Normal progress mutations go through `/lessons/{id}/complete` and `/lessons/{id}/quiz/submit`.
         */
        patch: operations["adminPatchUserStats"];
        trace?: never;
    };
    "/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List learning modules
         * @description [PostgREST] `GET /rest/v1/modules?select=*,lessons(*)&order=order_index`. Filter by level: `&level=eq.A1`. Public — no auth required.
         */
        get: operations["listModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a module by id
         * @description [PostgREST] `GET /rest/v1/modules?id=eq.{moduleId}&select=*,lessons(*)`
         */
        get: operations["getModule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lessons
         * @description [PostgREST] `GET /rest/v1/lessons?select=*&order=order_index`. Does NOT include quiz questions (use /lessons/{id} for that). `correct_answer` column is hidden from this role via RLS/view.
         */
        get: operations["listLessons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get lesson detail (vocabulary, grammar, quiz questions — no correctAnswer)
         * @description [PostgREST] `GET /rest/v1/lessons?id=eq.{lessonId}&select=*,vocabulary(*),grammar(*,examples(*)),quiz_questions(*)`. The `quiz_questions` view strips `correct_answer` — scoring is server-side only.
         */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a lesson as read/completed after studying content
         * @description [Edge Function] Idempotent. If `lessonId` not already in `user_stats.completed_lessons`, appends it and awards +15 XP. Uses service role key internally to write stats.
         */
        post: operations["completeLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quiz questions for a lesson (no correctAnswer)
         * @description [PostgREST] Same as fetching lesson quiz via `/lessons/{id}` but returns only question data. `correct_answer` is excluded by the `quiz_questions_public` view / column-level security. Can be called without auth (lesson content is public).
         */
        get: operations["getLessonQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit quiz answers and update progress
         * @description [Edge Function] Scores answers server-side using service role key to read `correct_answer`. Scoring rules:
         *     - **score ≥ 80%** → lesson marked complete, +30 XP awarded, streak incremented.
         *     - **Streak logic**: if `user_stats.last_played_date` is today → no streak change;
         *       if yesterday → +1 streak; if older → reset streak to 1.
         *
         *     - `last_played_date` is always updated to today on any submission.
         */
        post: operations["submitQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard summary for the current user
         * @description [Edge Function] Aggregates: user profile, stats, next suggested lesson (first incomplete lesson by order_index), level-by-level progress, and last 5 quiz scores.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get roadmap with per-lesson completion and lock state
         * @description [Edge Function] Computes `status` (completed/current/locked) for each lesson by comparing `user_stats.completed_lessons` against all lessons ordered by `order_index`. A lesson is `locked` if the previous lesson is not completed.
         */
        get: operations["getRoadmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/testimonials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List landing page testimonials
         * @description [PostgREST] `GET /rest/v1/testimonials?order=order_index`
         */
        get: operations["listTestimonials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List landing page FAQs
         * @description [PostgREST] `GET /rest/v1/faqs?order=order_index`
         */
        get: operations["listFaqs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Level: "A1" | "A2" | "B1";
        User: {
            /**
             * Format: uuid
             * @description Maps to `auth.users.id` in Supabase
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @example hocvien@deutschpath.vn
             */
            email: string;
            /** @example Nguyễn Văn Lâm */
            fullName: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        /** @description Fields that a user may update on their own profile. */
        UserProfilePatch: {
            fullName?: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        UserStats: {
            /** @example 120 */
            xp: number;
            /** @example 4 */
            streak: number;
            /** Format: date */
            lastPlayedDate?: string;
            /**
             * @example [
             *       "a1-l1"
             *     ]
             */
            completedLessons: string[];
            /**
             * @example {
             *       "a1-l1": 100
             *     }
             */
            quizScores: {
                [key: string]: number;
            };
        };
        UserStatsPatch: {
            xp?: number;
            streak?: number;
            /** Format: date */
            lastPlayedDate?: string;
            completedLessons?: string[];
            quizScores?: {
                [key: string]: number;
            };
        };
        VocabularyItem: {
            de: string;
            pronunciation: string;
            vi: string;
            exampleDe: string;
            exampleVi: string;
        };
        GrammarExample: {
            de: string;
            vi: string;
        };
        GrammarExplanation: {
            title: string;
            rule: string;
            examples: components["schemas"]["GrammarExample"][];
        };
        /** @enum {string} */
        QuizQuestionType: "multiple-choice" | "fill-blank" | "matching" | "listening";
        MatchingPair: {
            de: string;
            vi: string;
        };
        QuizQuestionPublic: {
            id: string;
            type: components["schemas"]["QuizQuestionType"];
            questionText: string;
            /** @description Text the frontend may play via SpeechSynthesis for listening questions. */
            audioText?: string;
            options?: string[];
            matchingPairs?: components["schemas"]["MatchingPair"][];
            explanation: string;
        };
        /** @description Lightweight lesson representation used in lists, dashboard, and roadmap. */
        LessonSummary: {
            /** @example a1-l1 */
            id: string;
            /** @example m-a1-1 */
            moduleId: string;
            moduleTitle: string;
            level: components["schemas"]["Level"];
            title: string;
            titleVi: string;
            /** @example 05:40 */
            duration: string;
            /** @description Global lesson order across all modules. Used to determine next/prev lesson. */
            orderIndex: number;
            /**
             * @description ID of the next lesson by orderIndex. Null if this is the last lesson.
             * @example a1-l2
             */
            nextLessonId?: string | null;
        };
        /** @description Full lesson detail including vocabulary, grammar, and quiz questions. */
        Lesson: {
            /** @example a1-l1 */
            id: string;
            /** @example m-a1-1 */
            moduleId: string;
            moduleTitle: string;
            level: components["schemas"]["Level"];
            title: string;
            titleVi: string;
            /** @example 05:40 */
            duration: string;
            objective: string;
            summary: string;
            youtubeId?: string;
            /** @description Global lesson order across all modules. */
            orderIndex: number;
            /** @description ID of the next lesson. Null if this is the last lesson. */
            nextLessonId?: string | null;
            vocabulary: components["schemas"]["VocabularyItem"][];
            grammar: components["schemas"]["GrammarExplanation"];
            /** @description Quiz questions WITHOUT correctAnswer — scoring is server-side. */
            quiz: components["schemas"]["QuizQuestionPublic"][];
        };
        Module: {
            /** @example m-a1-1 */
            id: string;
            level: components["schemas"]["Level"];
            title: string;
            titleVi: string;
            lessons: components["schemas"]["Lesson"][];
        };
        /**
         * @description One answer per question. Use the appropriate field based on question type:
         *     - **multiple-choice** / **fill-blank** / **listening** → set `answer` (string).
         *       For fill-blank the server normalises case and trims whitespace before comparing.
         *
         *     - **matching** → set `matchedPairs` (array of de/vi pairs the user connected).
         *       Do NOT set `answer` for matching questions.
         */
        QuizAnswer: {
            questionId: string;
            /** @description Used for: multiple-choice (selected option text), fill-blank (typed value), listening (selected option text). Leave empty for matching type. */
            answer?: string;
            /** @description Used ONLY for matching type. Send all de/vi pairs the user connected. Server checks each pair against stored correct pairs. */
            matchedPairs?: components["schemas"]["MatchingPair"][];
        };
        QuizSubmission: {
            answers: components["schemas"]["QuizAnswer"][];
        };
        QuizQuestionResult: {
            questionId: string;
            correct: boolean;
            userAnswer: string;
            questionText: string;
            explanation: string;
            /** @description Optional. Return only after submission if you want the UI to show correction details. */
            correctAnswer?: string;
        };
        QuizResult: {
            lessonId: string;
            scorePercentage: number;
            passed: boolean;
            correctCount: number;
            totalQuestions: number;
            /** @example 30 */
            xpAwarded?: number;
            streakIncremented?: boolean;
            results: components["schemas"]["QuizQuestionResult"][];
            stats: components["schemas"]["UserStats"];
        };
        ProgressMutationResponse: {
            lessonId: string;
            alreadyCompleted: boolean;
            /** @example 15 */
            xpAwarded: number;
            stats: components["schemas"]["UserStats"];
        };
        DashboardSummary: {
            user: components["schemas"]["User"];
            stats: components["schemas"]["UserStats"];
            /** @description First lesson not yet in `completed_lessons`, ordered by `order_index`. Returns `LessonSummary` (not full Lesson) to keep the dashboard response lightweight. */
            nextSuggestedLesson: components["schemas"]["LessonSummary"];
            levelProgress: {
                level: components["schemas"]["Level"];
                completedLessons: number;
                totalLessons: number;
                progressPercentage: number;
            }[];
            recentScores: {
                lessonId: string;
                title: string;
                score: number;
            }[];
        };
        Roadmap: {
            overallProgress: {
                completedLessons: number;
                totalLessons: number;
                progressPercentage: number;
            };
            levels: {
                level: components["schemas"]["Level"];
                title: string;
                description: string;
                completedLessons: number;
                totalLessons: number;
                progressPercentage: number;
                lessons: components["schemas"]["RoadmapLesson"][];
            }[];
        };
        RoadmapLesson: {
            /** @description Lightweight summary — full detail loaded on demand via /lessons/{id} */
            lesson: components["schemas"]["LessonSummary"];
            /**
             * @description - `completed`: lessonId in user_stats.completed_lessons - `current`: first lesson not completed (there is only one at a time) - `locked`: not completed and not current
             * @enum {string}
             */
            status: "completed" | "current" | "locked";
        };
        Testimonial: {
            name: string;
            role: string;
            content: string;
            /** Format: uri */
            avatarUrl?: string;
        };
        FaqItem: {
            question: string;
            answer: string;
        };
        MessageResponse: {
            message: string;
        };
        ErrorResponse: {
            code?: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        LevelQuery: components["schemas"]["Level"];
        /** @example m-a1-1 */
        ModuleId: string;
        /** @example a1-l1 */
        LessonId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfilePatch"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    adminPatchUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example usr_123 */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatsPatch"];
            };
        };
        responses: {
            /** @description Updated stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Forbidden — service role key required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listModules: {
        parameters: {
            query?: {
                level?: components["parameters"]["LevelQuery"];
                /** @description When false, omit the nested lessons array (lighter response for nav/sidebar). */
                includeLessons?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Module"][];
                    };
                };
            };
        };
    };
    getModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m-a1-1 */
                moduleId: components["parameters"]["ModuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Module"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLessons: {
        parameters: {
            query?: {
                level?: components["parameters"]["LevelQuery"];
                moduleId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LessonSummary"][];
                    };
                };
            };
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example a1-l1 */
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    completeLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example a1-l1 */
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completion recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressMutationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLessonQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example a1-l1 */
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quiz questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lessonId: string;
                        questions: components["schemas"]["QuizQuestionPublic"][];
                    };
                };
            };
        };
    };
    submitQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example a1-l1 */
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmission"];
            };
        };
        responses: {
            /** @description Quiz result and updated stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRoadmap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roadmap state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTestimonials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Testimonials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Testimonial"][];
                    };
                };
            };
        };
    };
    listFaqs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FAQ entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["FaqItem"][];
                    };
                };
            };
        };
    };
}
